# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: CI

on:
  push:
    branches:
      - master

jobs:
  ci_job:

    runs-on: ubuntu-latest

    steps:
    
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Unit tests
      run: mvn -B clean test

    - name: Integration tests
      run: mvn -B failsafe:integration-test
